stages:
- build


before_script:
- ""


build_sassy:
  image: python:latest
  stage: build
  script:
    - pip install twine
    - python setup.py sdist bdist_wheel
    - TWINE_PASSWORD=${HALIA_CA_PYPI_TOKEN} TWINE_USERNAME=halia-ca-pypi-token python -m twine upload --repository-url ${CI_API_V4_URL}/projects/13566696/packages/pypi dist/*
  when: manual
  tags:
  - halia
  - k8s 