# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
- test
- deploy1
- deploy2
- deploy3
- deploy

image: python:3.8-slim

pages:
  stage: deploy
  script:
    - pip install -r requirements.txt
    - sphinx-build -d _build/doctrees . _build/html
    - mv _build/html public
  artifacts:
    paths:
      - public
  only:
    - dev
  tags:
    - halia
    - k8s
# include:
# - template: Security/SAST.gitlab-ci.yml


trigger_pipeline1:
  stage: deploy1
  script: 
    - echo "deploy 1 => $CI_PIPELINE_SOURCE"
  rules:
    - if: $CI_PIPELINE_SOURCE == 'pipeline'

trigger_pipeline2:
  stage: deploy2
  script: 
    - echo "deploy 2 => $CI_PIPELINE_SOURCE"
  rules:
    - if: $CI_PIPELINE_SOURCE == 'trigger'

trigger_pipeline3:
  stage: deploy3
  script: 
    - echo "deploy 3 => $CI_PIPELINE_SOURCE"
  rules:
    - if: $CI_PIPELINE_SOURCE == 'other'
