# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
  - merge-request
  - build-docs
  - deploy
  - trigger

default:
#  image: python:latest
  image: registry.gitlab.com/halia-ca/pypi:latest

before_script:
  - pip install -r requirements.txt

pages:
#  image: python:latest
  stage: build-docs
  script:
    - sphinx-build -b html docs/source public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  tags:
    - halia
    - k8s

merge-request-no-main:
  stage: merge-request
  script:
    - coverage run -m pytest -v tests/
    - coverage report -m
    - coverage xml
    - flake8 src/ sassy.py
    - pycodestyle src/ sassy.py
    - pydocstyle src/ sassy.py
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != $CI_DEFAULT_BRANCH
  artifacts:
    reports:
      cobertura: coverage.xml

merge-request-main:
  stage: merge-request
  script:
    - coverage run -m pytest -v tests/
    - coverage report -m
    - coverage xml
    - flake8 src/ sassy.py
    - pycodestyle src/ sassy.py
    - pydocstyle src/ sassy.py
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
  artifacts:
    reports:
      cobertura: coverage.xml


deploy:
  stage: deploy
  script:
    - coverage run -m pytest -v tests/
    - coverage report -m
    - coverage xml
    - flake8 --format=json --exit-zero --output-file=gl-code-quality-report.json src/ sassy.py
    - pycodestyle src/ sassy.py
    - pydocstyle src/ sassy.py
    - python3 setup.py sdist bdist_wheel
    - python3 -m twine upload --skip-existing --repository gitlab dist/*-py3-none-any.whl
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != $CI_DEFAULT_BRANCH
  artifacts:
    reports:
      cobertura: coverage.xml
      codequality: gl-code-quality-report.json

#  Python to exe
#  pyinstaller --noconfirm --onedir --console --add-data "/Volumes/SSD_Data/halia/Sassy/src:src/" --hidden-import "colorlog"  "/Volumes/SSD_Data/halia/Sassy/sassy.py"
